weights: /home/rajivp/yolov5_htp/yolov5/personf_09222022-x/exp/weights/best.pt
cfg: ''
data: /home/rajivp/image-datasets/HTP-main/2cycle/PersonF/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 100
batch_size: -1
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '1'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: personf_10072022-x
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: personf_10072022-x/exp
